pik-piam/remind

- DESCRIPTION
- R/compareScenarios.R
- R/reportPolicyCosts.R
- Adds the variable `Policy Cost|Consumption Loss|Relative to Reference Consumption (percent)` to the reporting as suggested by Robert.
- Adds a plot of this variable to the `compareScenarios` script.
> Add relative Consumption Loss Variable and Plot

- DESCRIPTION
- R/reportFE.R
that were accidentially not renamed in a808c0ec9839bcfebf82f293e60d4a29f072d3e5
> Fix some variables in Industry Sector Reporting 

- DESCRIPTION
- R/reportCrossVariables.R
- R/reportFE.R
- Aggregate transport fuel variables, `FE|Transport|<fueltype>` and `FE|Transport|{Pass|Freight}|<fueltype>` are now reported based on FE variables in `complex`.
- Derived variables in `crossVariables.R` are now reported consistently accross transport realizations, based on the aforementioned aggregates.
> Improve Transport Sector Fuel Reporting

- DESCRIPTION
- R/reportEDGETransport.R
Previously EDGE-T reporting aggregated ES demand in terms of fuel types.
For the LCA coupling, this does not make much sense, so reporting is aggregated in terms of drivetrain technology (basically the categories are given by EDGE-T).
> Reporting EDGE-T Energy Services by Drivetrain

- DESCRIPTION
- R/compareScenarios.R
- Issue was caused by additional `GDP|PPP` variables in `historical.mif` (maybe some recent update @LaviniaBaumstark) or a change in how this is handled by `data.table::dcast`.
- We use IMF data for `GDP|PPP` historical plots in linegraphs in `compareScenarios.R`.
> GDP Linegraph Bugfix

- DESCRIPTION
- R/compareScenarios.R
- the model for population data was not included in the dataset filter, see #27.
- add a list with models for data in the historical dataset, `histmap`. If data
from the historical dataset is to be plotted via `lineplots_perCap`, the
variable and the model should be added to `histmap`.
> CompareScenarios: Restore plots of historical data in linegraphs

- DESCRIPTION
- R/reportTax.R
This reflects an earlier change in REMIND tax recycling. Here the tax revenue from CO2 LUC is handled separately. "Taxes|GHG emissions|GAMS calculated" now contains the full revenue again, and there are two new reporting variables for the tax revenue w/o CO2 LUC and tax revenue from CO2 LUC
> fixed reporting variable "Taxes|GHG emissions|GAMS calculated" 

- DESCRIPTION
- R/reportSE.R
Now there is a variable `SE|Gases|Waste`, so that the sum of subcategories for `SE|Gases` adds up.
This PR is related (but not strictly depending on) https://github.com/remindmodel/remind/pull/116
> Correctly report SE|Gases contribution from Landfills

- .Rbuildignore
- DESCRIPTION
- README.md
- tests/testthat/test-convGDX2mif.R
- Add README.
- Add Anastasis recipe for testing backward compatibility to README.
- Add `old.gdx` to `inst/extdata`. Add the file to buildignore, so that it is not inflating the size of the installed package.
- Slightly modify the test script to have a more convenient interface.
> Add old GDP file for testing backward compatibility.

- DESCRIPTION
- R/reportTechnology.R
- README.md
See issue #32 
Tested against recent `fulldata.gdx` and `old.gdx`.
> Fix warnings from comparison scalar vs vector in reportTechnology

- DESCRIPTION
- R/reportEmi.R
Fix reporting of non-electric energy supply emissions, Supply|Non-Elec before referred to gross emissions, now refers to net emissions and introduced Supply|Non-Elec|Gross to refer gross emissions.
Add distinction between atmospheric and fossil captured carbon for CCU. Add biogenic captured CO2 from industry CCS to CCU and CDR variables.
> Emi ccu reporting

- DESCRIPTION
- R/reportFE.R
- R/reportSE.R
This is required to calculate PE demand shares for gases on the FE level.
Example: You want to calculate the share of gas from coal gasification for industry.
```
FE|Industry|Gases 
x FE|Buildings and Industry|Gases|Non-Biomass / FE|Buildings and Industry|Gases # this is the share of segafos.fegas.tdfosgas in fegas
x SE|Gases|Coal / SE|Gases|Non-Biomass # the share of coal in segafos
```
Note that, in order to have accurate reporting, at least one reporting variable should exist for every important variable in GAMS.
> Report Gases from non-bio Origin, i.e., segafos

- DESCRIPTION
- R/reportCrossVariables.R
- R/reportEDGETransport.R
- R/reportFE.R
- Add variables required for the AR6 data template to the output file.
- Fix a unit error in the EDGE-T reporting, previously there were million pkm/tkm reported instead of billions.
> Add AR6 Variable to EDGE-T reporting

- DESCRIPTION
- R/reportFE.R
- R/reportTechnology.R
This PR contains two bugfixes:
- fixed year inconsistency for  v_prodEs[,y,]
- the object int2ext[i2e] was giving back a list element, and not a character vector. using "[[" instead of "[" was therefore necessary
> Bugfixes on reportFE and reportTechnology

- DESCRIPTION
- R/reportEDGETransport.R
This pull request contains:
-  a bugfix in how the share of transport energy demand is calculated
- hopefully a correct accounting of synfuels and hydrogen emissions
- emissions from electricity (direct use) and NG (direct use) in the system emissions calculation
- added global values to reporting for FE and ES EDGE-Transport
> Bugfixes in EDGE-transport reporting and global values added

- DESCRIPTION
- R/reportEDGETransport.R
This is required to comply with REMIND's default output (MIF) format for the addition of EDGE-Transport variables.
> Add trailing semicolon to EDGE-Transport reporting

- DESCRIPTION
- R/reportCrossVariables.R
- `Intensity|Final Energy|CO2` is reported twice, once with `Mt CO2/EJ`,
once with `Mt CO2-equiv/EJ`
- both variables differ in their calculation
- `Intensity|Final Energy|CO2` with `Mt CO2-equiv/EJ` is renamed
`Intensity|Final Energy|GHG`
/close #64
> fix duplicate variable names

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportCrossVariables.R
- R/reportFE.R
Biomass quantities have previously been derived from biomass share in SE|Liquids, but the biofuels can be distributed quite unevenly across sectors. Hence, the specific quantities (`seliqbio.fepet.tdbiopet` etc) have to be reported.
> Correctly report biomass shares in complex and EDGE-T Liquids

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportEDGETransport.R
This PR contains the reporting of the "Demand" emissions for transport sub-categories. Meaning: only fossil fuels tailpipe emissions, excluding biofuels and synfuels, that are accounted for are 0 emissions fuels.
> Added Demand emissions to reportEDGETransport.

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportEmi.R
For details on the problem, see here:
https://github.com/remindmodel/development_issues/issues/20
Instead of reading emission factor from the GDX, as a temporary workaround we set them directly in `reportEmi.R`, consistent with the values before commit https://github.com/remindmodel/remind/commit/934783750931eb2b3e6c64b5b65b139522d4b70a
> Temporary fix for emission factors to correctly report Supply Variables to AR6

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportEmi.R
- README.md
Fix energy emissions reporting such that it adds up, introduce Emi|CO2|Energy|Supply and Emi|CO2|Energy|Demand. Introduce Emi|CO2|Transport|Direct to avoid confusion of energy demand emissions (same name as direct emissions of other sectors). However, this variable is the same as Emi|CO2|Transport|Demand.
> Fix energy emissions reporting such that it adds up

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/compareScenarios.R
- R/validationSummary.R
Addition of gases in transport in plots. Calculates the total FE in transport as sum of liquids+gases+hydrogen+electricity (instead of misleading for the moment sub-categories of liquids)
> Added transport gases in summary and compare scenarios plot.

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportCrossVariables.R
- R/reportFE.R
- README.md
This improves the calculation of FE synfuel variables in the reporting. New variables are introduced "FE|Transport|Liquids|LDV|Synthetic|New Reporting (EJ/yr)" ..., distinguishing between synfuels, biofuels and fossil fuels on FE transport liquids and gases level for LDV and HDV. The old transport synfuel variables were removed.
> Fix FE synfuel reporting transport

- .zenodo.json
- DESCRIPTION
- R/reportEmi.R
- README.md
This fixes the calculation of energy supply emissions when CCU is on. CO2 flows of CCU were accidentally substracted from energy supply emissions before. Gross non-electric supply emissions should not be negative anymore now.
> fix energy supply emissions w/ CCU

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportCrossVariables.R
- R/reportFE.R
It turns out our `FE|Transport|Liquids` totals do not add up. The reason has been the *old fashioned* calculation of the `Oil` sub-compartment.
> Fix calculation of the transport liquids from oil.

- .Rbuildignore
- .buildlibrary
- .zenodo.json
- DESCRIPTION
- tests/testthat/test-convGDX2mif.R
Integrate a first fully automated test for the call to `convGDX2MIF`. GDXs are shipped in the folder `tests/testgdxs`.
A first data integrity check is performed on the output, by specifying a list of the form
```
list(
`FE|Transport|Liquids (EJ/yr)` = "`FE|Transport|Liquids|Oil (EJ/yr)` + `FE|Transport|Liquids|Biomass (EJ/yr)` + `FE|Transport|Liquids|Hydrogen (EJ/yr)` + `FE|Transport|Liquids|Coal (EJ/yr)`")
```
This is done by using `data.table` at the moment. For full RSE support, I'd opt for `quitte::calc_addVariables` instead, but there seem to be an issue with `quitte::as.quitte` and I could not successfully convert the magclass object.
This is intended as a first stab and comments & suggestions are welcome!
> First automated tests including a template for data integrity checks

- .Rbuildignore
- .buildlibrary
- .zenodo.json
- DESCRIPTION
- README.md
- tests/testthat/test-convGDX2mif.R
A small patch to the last PR, now using a PIK user homepage instead of a "random web service" to provide the test GDXs. There is also an update to the README which points to the possibility to manually put GDX in `tests/testgdxs` instead of the download.
> Amendment to the last PR: Use PIK Webpages for Download

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportFE.R
`FE|Transport|Pass` was incorrect. It is derived from `FE|Transport|non-LDV` which was wrongly derived from the freight share in liquids, omitting trains.
> Fix transport pass totals

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/reportEmi.R
- README.md
- tests complete without failure
- `lucode2::buildLibrary()` is still confused about the differences between warnings and errors, refuses to update all the fluff file
- I won't clean up the entire package to get it to build
> fix 33b766a and include updated v_co2capturevalve values instead of ignoring them
