DESCRIPTION, R/compareScenarios.R
- the function lineplots_perCap can now be used to produce
regional/global versions of lineplots with time or GDP on the x-axis
and historical data.
- the indentation is rectified.
- `lineplots_perCap` would be a candidate for the mip library...
=> Refactoring of compareScenarios.

R/reportExtraction.R
(function reportExtraction.R)
Associated ticket #16: Variable "Res|Average Extraction Costs|XXX" is not reported for realisation 31_fossil:grades2poly (the default)
=> Fix bug in the reporting of average extraction costs

DESCRIPTION, R/compareScenarios.R
see https://gitlab.pik-potsdam.de/REMIND/validation/issues/43
- add f-gases to GHG overview plot
- add f-gases to emission details section
=> Add F-Gases to compareScenarios.

DESCRIPTION, R/reportEDGETransport.R
CO2 emissions for different transport modes are added to the EDGE-Transport reporting.
=> Added CO2 emissions for different transport modes.

DESCRIPTION, R/reportFE.R
Added floorspace projections in the reporting
=> Floorspace projections

DESCRIPTION, R/reportEDGETransport.R
The rescaling by a factor of 1e3 was not correct.
=> Fix transport vkm

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportCapacity.R, README.md
Felix, I had to create a new PR with your changes because in the meantime other changes: f4176a9686c1974ddf9d0f9f4cd15f19a52e936f came along. Can you close yours and accept this one?
=> Fix battery and hydrogen capacity reporting. Scaling in reporting of storspv/storwind to battery capacities changed by RP.

.buildlibrary, .zenodo.json, DESCRIPTION, R/compareScenarios.R, R/reportCapacity.R, README.md
Add synfuel liquids and gases to SE mix plots in compare scenario script. Add capacity additions of liquids and gases to reporting.
=> Synfuel report

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportEDGETransport.R
category to be consistent with US standards, see, e.g., https://en.wikipedia.org/wiki/Vehicle_size_class
=> Shift Compact cars to medium size category and Midsize to large

DESCRIPTION, R/reportEmi.R, R/reportFE.R, R/reportSE.R, README.md
improve CCU reporting and add SE electrolysis variables
=> improve CCU reporting and add SE electrolysis variables

.buildlibrary, .zenodo.json
add missing built files
Sry Anastasis!
=> add missing build files

.buildlibrary, .zenodo.json, DESCRIPTION, R/compareScenarios.R, R/reportEmi.R, README.md
small bugfixes CCU emissions and compareScenario
=> small bugfixes CCU emissions and compareScenario

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportEmi.R, README.md
=> Demand emi fix

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportFE.R
- Account for otherFEdemands.
- Add variables also in case there is no synfuel module activated.
=> Fix the reporting of FE|Transport|Liquids|Hydrogen

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportLCOE.R, README.md
This fixes some bugs in the LCOE reporting. Most notably, the renewable capacity factors are now calculated more precisely and the representation of average LCOE integration cost (incl. storage, grid and curtailment) cost has been refined.
=> update LCOE reporting

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportEDGETransport.R
This PR contains the adjustments to make the reporting regional compatible.
=> Regional EDGE-T reporting.

.buildlibrary, .zenodo.json, DESCRIPTION, tests/testthat/test-convGDX2mif.R
and add binary mode for the download for WIN compatibility.
=> Remove MD5 check on downloads (now that we get them from RSE anyways)

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportPrices.R, README.md
Transport prices were not calculated correctly when edge_esm was used as realization for the transport module, this is fixed now.
=> Bugfix transport FE prices with edge_esm

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportEDGETransport.R
The biofuel shares for all liquids were calculated from the biofuel shares in the LDV sector only, leading to lower emissions from all transport.
=> Fix emission reporting bug for EDGE-T CO2 emission calculation.

.buildlibrary, .zenodo.json, DESCRIPTION, R/reportEDGETransport.R
to be consistent with reportEmi.R
=> Fix emission factors also in the EDGE-T reporting script
